wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    code_path: code/code/train.py
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1657258255
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      4: 3.7.12
      5: 0.12.16
      6: 4.18.0
      8:
      - 5
      11:
      - 1
